replicaCount: 1
# v1.2.0-660ae95
image:
  registry: "ghcr.io"
  repository: "vit-um/kbot"
  pullPolicy: IfNotPresent # Дозволяє замінити образ за замовчуванням
  tag: v1.3.0-c9bf7ee
  os: linux
  arch: amd64
  parameter: go
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "6552467449:AAFGGy7ZtDv9iDLftLy1_1p1ySKMI3dyF40"
  # "token"
securityContext:
  privileged: true
